### ISSUE TITLE
irisにおいて、NIP-36非対応クライアントであるにも関わらず、画像が表示される

### ISSUE THREAD

**Issue by Memory-of-Snow** [ryogrid/NostrNIP36ImageRedirector#1]
**バグの説明**
irisを利用すると、NIP-36非対応クライアントであるにも関わらず、画像が表示される

**再現手順**
発生させる手順を説明してください:
1.NIP-36対応クライアントからCW込みでポストを投稿する
2. irisで投稿したポストを表示する

**期待される挙動**
画像を見ることができない状態であってほしい。

**デスクトップ （該当する場合は以下の情報を埋めてください）:**
 - OS: Windows10
 - ブラウザ: Chrome
 - バージョン: 114.0.5735.199

**追加情報**
キャッシュが悪さをしているのかと思い、別のブラウザ上のirisで対応ポストを表示してみましたが、やはり表示される状態でした。

**Comment by ryogrid** [comment]
@Memory-of-Snow 
報告ありがとうございます。  
　
1点確認なのですが、以下の条件はあったりしますでしょうか？
- 同一のネットワークにて、直近数時間程度の範囲でNIP-36対応クライアントを動作させた

--- 

現在以下のような処理が入っており、場合により非対応クライアントでも表示が行われます。
- NIP-36対応クライアントで1度、本プログラム経由で画像アクセスをした場合、ある程度の期間、本プログラムはIPアドレスを記憶
- IPアドレスが記憶されている間に同一のネットワークからリクエストが来た場合、一部の特定が可能な非対応クライアントを除いてアクセスを通す
  
上記を行っている理由は以下です。
- Webクライアントにおいて、ユーザが表示している画像をクリック（or タッチ）した場合、画像がブラウザの別タブ（もしくはウィンドウ）で開くという挙動をする場合が多い
- 上のような処理が行われた場合、本プログラムへのリクエストにリファラーが付加されないため、クライアントの判別ができず、アクセスを弾いてしまうが、本プログラムを介す形にした場合のみこのようなことが発生することは望ましくない
- これを解決するために、あるIPアドレスからのアクセスがNIP-36対応クライアントからのものであった場合、続く同一IPアドレスからのリクエストは同一クライアントのものであると仮定し、ある程度の期間は通すようにする

ただ、ご指摘のような体験をするケースは他にも聞いており、上記の対処を取り除く、もしくは他の対処方法の実装を検討する必要があるかとも考えているところです。

**Comment by Memory-of-Snow** [comment]
はい、同一のPCの別ブラウザ上のクライアント(NIP36対応)で表示を行いました。
仕様通りの挙動なのですね。
今回はテストとして試したのみなので、不愉快な思い等はありません。
お手数をおかけしました。


2023年7月18日(火) 8:16 Ryo Kanbayashi ***@***.***>:
